@desktop_switcher_HostAddress = http://localhost:5093

GET {{desktop_switcher_HostAddress}}/weatherforecast/
Accept: application/json

###

PUT {{desktop_switcher_HostAddress}}/switch-desktop
Accept: application/json
Content-Type: application/json

{
  "desktopType": "default"
}

###

PUT {{desktop_switcher_HostAddress}}/switch-desktop
Accept: application/json
Content-Type: application/json

{
  "desktopType": "secured"
}